# Book settings
title: "PyEngineering"
author: "Binayak Basu"
logo: images/logo.png # optional, add a logo inside images/
copyright: "2025"

# HTML-specific settings
html:
  favicon: images/favicon.ico # optional
  home_page_in_navbar: true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

# Repository settings (optional, useful for GitHub)
repository:
  url: https://github.com/basu-binayak/PyEngineering.git
  path_to_book: "" # leave blank if root
  branch: main

# Execution options
execute:
  execute_notebooks: auto # options: auto, force, cache, off
  timeout: 60 # seconds per notebook cell

# Parse settings
# Sphinx / HTML settings
sphinx:
  config:
    language: en
    html_theme: sphinx_book_theme
    html_show_sphinx: true
    html_show_copyright: true
    copyright: "© 2025 Binayak Basu. All rights reserved."

# Extra features
latex:
  latex_documents:
    targetname: book.tex
